name: docker-build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./build_docker.sh

    - name: Test docker run
      run: docker run --rm --volume=$(pwd):/flownet2-pytorch:rw --workdir=/flownet2-pytorch $USER/flownet2:latest echo 'test'
